export const POST_LOGIN = 'POST_LOGIN';
export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';
export const UPDATE_LOGIN_ERROR = 'UPDATE_LOGIN_ERROR';
export const UPDATE_ACCOUNT_DIALOG_ACTIVE_TAB = 'UPDATE_ACCOUNT_DIALOG_ACTIVE_TAB';
export const UPDATE_USER = 'UPDATE_USER';
