export const POST_LOGIN = 'POST_LOGIN';
export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';
export const UPDATE_LOGIN_ERROR = 'UPDATE_LOGIN_ERROR';
export const UPDATE_ACCOUNT_DIALOG_ACTIVE_TAB = 'UPDATE_ACCOUNT_DIALOG_ACTIVE_TAB';
export const UPDATE_USER = 'UPDATE_USER';
export const CLOSE_LOGIN_DIALOG = 'CLOSE_LOGIN_DIALOG';
export const OPEN_LOGIN_DIALOG = 'OPEN_LOGIN_DIALOG';
